apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: helloworld
  description: A Hello World application
  annotations:
    backstage.io/techdocs-ref: url:techdocs://default/helloworld
    backstage.io/managed-by-location: url:http://github.com/backstage/backstage/blob/master/catalog-info.yaml
spec:
  type: service
  lifecycle: production
  owner: my-team
