apiVersion: backstage.io/v1beta2
kind: Component
metadata:
  name: helloworld
  description: A Hello World application
  annotations:
    backstage.io/techdocs-ref: url:techdocs://default/helloworld
spec:
  type: service
  lifecycle: production
  owner: my-team
