apiVersion: backstage.io/v1beta2
kind: Component
metadata:
  name: my-service
  description: A description of my service
  annotations:
    backstage.io/techdocs-ref: url:techdocs://default/my-service
spec:
  type: service
  lifecycle: production
  owner: my-team
