apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: helloworld
  description: A simple hello world application
  annotations:
    backstage.io/ci-cd: 'github-actions'
    github.com/ci-cd-url: 'https://github.com/SilkyKumari/helloworld/actions'

spec:
  type: service
  lifecycle: production
  owner: team@example.com
  system: my-system
  ci:
    - url: https://github.com/SilkyKumari/helloworld/actions
      name: GitHub Actions
      type: github-actions
